In [4]:
import pandas as pd
import datetime
import pandas.io.data as web
import matplotlib.pyplot as plt
from matplotlib import style

style.use('fivethirtyeight')

start = datetime.datetime(2010,1,1)
end = datetime.datetime(2015,8,22)

df = web.DataReader('XOM','yahoo', start, end)
df['High'].plot()
plt.legend()
plt.show()

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style

style.use('fivethirtyeight')

web_stats = {'Day':[1,2,3,4,5,6],
             'Visitors':[43,34,65,56,29,76],
             'Bounce Rate':[65,67,78,65,45,52]}

df = pd.DataFrame(web_stats)
df.set_index('Day', inplace=True)

df.plot()
plt.show()

In [16]:
import pandas as pd

df = pd.read_csv('ZILL-Z77006_A.csv')
df.set_index('Date', inplace = True)

df.to_csv('newcsv2.csv')

In [18]:
df = pd.read_csv('newcsv2.csv', index_col = 0)
print(df.head())

               Value
Date
2016-02-29  451300.0
2016-01-31  451200.0
2015-12-31  450800.0
2015-11-30  451000.0
2015-10-31  452600.0

In [22]:
df.columns = ['House_Prices']
print(df.head())
df.to_csv('newcsv3.csv')

            House_Prices
Date
2016-02-29      451300.0
2016-01-31      451200.0
2015-12-31      450800.0
2015-11-30      451000.0
2015-10-31      452600.0

In [23]:
df.to_csv('newcsv4.csv', header=False)

In [27]:
df = pd.read_csv('newcsv4.csv', names = ['date','house_price'], index_col=0)
print(df.head())

            house_price
date
2016-02-29     451300.0
2016-01-31     451200.0
2015-12-31     450800.0
2015-11-30     451000.0
2015-10-31     452600.0

In [28]:
df.to_html('example.html')

In [31]:
import Quandl

api_key = open('C:/Users/Matthew Madden/Documents/myquandlkey.txt','r').read()

df=Quandl.get("FMAC/HPI_TX", authtoken=api_key)

print(df.head())

                Value
Date
1975-01-31  32.663795
1975-02-28  33.001967
1975-03-31  33.606352
1975-04-30  34.472694
1975-05-31  34.740937

In [37]:
fiddy_states = pd.read_html('https://simple.wikipedia.org/wiki/List_of_U.S._states')
for abbv in fiddy_states[0][0][1:]:
    print('FMAC/HPI_'+str(abbv))

FMAC/HPI_AL
FMAC/HPI_AK
FMAC/HPI_AZ
FMAC/HPI_AR
FMAC/HPI_CA
FMAC/HPI_CO
FMAC/HPI_CT
FMAC/HPI_DE
FMAC/HPI_FL
FMAC/HPI_GA
FMAC/HPI_HI
FMAC/HPI_ID
FMAC/HPI_IL
FMAC/HPI_IN
FMAC/HPI_IA
FMAC/HPI_KS
FMAC/HPI_KY
FMAC/HPI_LA
FMAC/HPI_ME
FMAC/HPI_MD
FMAC/HPI_MA
FMAC/HPI_MI
FMAC/HPI_MN
FMAC/HPI_MS
FMAC/HPI_MO
FMAC/HPI_MT
FMAC/HPI_NE
FMAC/HPI_NV
FMAC/HPI_NH
FMAC/HPI_NJ
FMAC/HPI_NM
FMAC/HPI_NY
FMAC/HPI_NC
FMAC/HPI_ND
FMAC/HPI_OH
FMAC/HPI_OK
FMAC/HPI_OR
FMAC/HPI_PA
FMAC/HPI_RI
FMAC/HPI_SC
FMAC/HPI_SD
FMAC/HPI_TN
FMAC/HPI_TX
FMAC/HPI_UT
FMAC/HPI_VT
FMAC/HPI_VA
FMAC/HPI_WA
FMAC/HPI_WV
FMAC/HPI_WI
FMAC/HPI_WY

In [48]:
import pandas as pd

df1 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55]},
                   index = [2001, 2002, 2003, 2004])

df2 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55]},
                   index = [2005, 2006, 2007, 2008])

df3 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'Low_tier_HPI':[50, 52, 50, 53]},
                   index = [2001, 2002, 2003, 2004])

In [39]:
concat = pd.concat([df1,df2])
print(concat)

      HPI  Int_rate  US_GDP_Thousands
2001   80         2                50
2002   85         3                55
2003   88         2                65
2004   85         2                55
2005   80         2                50
2006   85         3                55
2007   88         2                65
2008   85         2                55

In [40]:
concat = pd.concat([df1,df2,df3])
print(concat)

      HPI  Int_rate  Low_tier_HPI  US_GDP_Thousands
2001   80         2           NaN              50.0
2002   85         3           NaN              55.0
2003   88         2           NaN              65.0
2004   85         2           NaN              55.0
2005   80         2           NaN              50.0
2006   85         3           NaN              55.0
2007   88         2           NaN              65.0
2008   85         2           NaN              55.0
2001   80         2          50.0               NaN
2002   85         3          52.0               NaN
2003   88         2          50.0               NaN
2004   85         2          53.0               NaN

In [41]:
df4 = df1.append(df2)
print(df4)

      HPI  Int_rate  US_GDP_Thousands
2001   80         2                50
2002   85         3                55
2003   88         2                65
2004   85         2                55
2005   80         2                50
2006   85         3                55
2007   88         2                65
2008   85         2                55

In [42]:
df4 = df1.append(df3)
print(df4)

      HPI  Int_rate  Low_tier_HPI  US_GDP_Thousands
2001   80         2           NaN              50.0
2002   85         3           NaN              55.0
2003   88         2           NaN              65.0
2004   85         2           NaN              55.0
2001   80         2          50.0               NaN
2002   85         3          52.0               NaN
2003   88         2          50.0               NaN
2004   85         2          53.0               NaN

In [44]:
s = pd.Series([80,2,50], index=['HPI','Int_rate','US_GDP_Thousands'])
df4 = df1.append(s,ignore_index=True)
print(df4)

   HPI  Int_rate  US_GDP_Thousands
0   80         2                50
1   85         3                55
2   88         2                65
3   85         2                55
4   80         2                50

In [98]:
import pandas as pd

df1 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55]},
                   index = [2001, 2002, 2003, 2004])

df2 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55]},
                   index = [2005, 2006, 2007, 2008])

df3 = pd.DataFrame({'HPI':[80,85,88,85],
                    'Unemployment':[7, 8, 9, 6],
                    'Low_tier_HPI':[50, 52, 50, 53]},
                   index = [2001, 2002, 2003, 2004])

In [99]:
print(pd.merge(df1,df2, on='HPI'))

   HPI  Int_rate_x  US_GDP_Thousands_x  Int_rate_y  US_GDP_Thousands_y
0   80           2                  50           2                  50
1   85           3                  55           3                  55
2   85           3                  55           2                  55
3   85           2                  55           3                  55
4   85           2                  55           2                  55
5   88           2                  65           2                  65

In [100]:
print(pd.merge(df1,df2, on=['HPI','Int_rate']))

   HPI  Int_rate  US_GDP_Thousands_x  US_GDP_Thousands_y
0   80         2                  50                  50
1   85         3                  55                  55
2   88         2                  65                  65
3   85         2                  55                  55

In [101]:
df4 = pd.merge(df1,df3, on='HPI')
df4.set_index('HPI', inplace=True)
print(df4)

     Int_rate  US_GDP_Thousands  Low_tier_HPI  Unemployment
HPI
80          2                50            50             7
85          3                55            52             8
85          3                55            53             6
85          2                55            52             8
85          2                55            53             6
88          2                65            50             9

In [102]:
df1.set_index('HPI', inplace = True)
df3.set_index('HPI', inplace = True)

joined = df1.join(df3)
print(joined)

     Int_rate  US_GDP_Thousands  Low_tier_HPI  Unemployment
HPI
80          2                50            50             7
85          3                55            52             8
85          3                55            53             6
85          2                55            52             8
85          2                55            53             6
88          2                65            50             9

In [103]:
df1 = pd.DataFrame({
                    'Int_rate':[2, 3, 2, 2],
                    'US_GDP_Thousands':[50, 55, 65, 55],
                    'Year':[2001, 2002, 2003, 2004]
                    })

df3 = pd.DataFrame({
                    'Unemployment':[7, 8, 9, 6],
                    'Low_tier_HPI':[50, 52, 50, 53],
                    'Year':[2001, 2003, 2004, 2005]})

In [104]:
merged = pd.merge(df1,df3, on='Year', how='left')
#left = equal to left outer join SQL (use keys from left frame only)
#right = right outer join from SQL (use keys from right frame only)
#outer = full outer join (use union of keys)
#inner = use only intersection of keys

merged.set_index('Year', inplace = True)
print(merged)

      Int_rate  US_GDP_Thousands  Low_tier_HPI  Unemployment
Year
2001         2                50          50.0           7.0
2002         3                55           NaN           NaN
2003         2                65          52.0           8.0
2004         2                55          50.0           9.0

In [105]:
merged = pd.merge(df1,df3, on='Year', how='right')

merged.set_index('Year', inplace = True)
print(merged)

        Int_rate  US_GDP_Thousands  Low_tier_HPI  Unemployment
Year
2001.0       2.0              50.0            50             7
2003.0       2.0              65.0            52             8
2004.0       2.0              55.0            50             9
2005.0       NaN               NaN            53             6

In [62]:
merged = pd.merge(df1,df3, on='Year', how='outer')

merged.set_index('Year', inplace = True)
print(merged)

        Int_rate  US_GDP_Thousands  Low_tier_HPI  Unemployment
Year
2001.0       2.0              50.0          50.0           7.0
2002.0       3.0              55.0           NaN           NaN
2003.0       2.0              65.0          52.0           8.0
2004.0       2.0              55.0          50.0           9.0
2005.0       NaN               NaN          53.0           6.0

In [63]:
merged = pd.merge(df1,df3, on='Year', how='inner')

merged.set_index('Year', inplace = True)
print(merged)

      Int_rate  US_GDP_Thousands  Low_tier_HPI  Unemployment
Year
2001         2                50            50             7
2003         2                65            52             8
2004         2                55            50             9

In [106]:
df1.set_index('Year', inplace=True)
df3.set_index('Year', inplace=True)
joined = df1.join(df3, how="outer")
print(joined)
print(joined.index)

      Int_rate  US_GDP_Thousands  Low_tier_HPI  Unemployment
Year
2001       2.0              50.0          50.0           7.0
2002       3.0              55.0           NaN           NaN
2003       2.0              65.0          52.0           8.0
2004       2.0              55.0          50.0           9.0
2005       NaN               NaN          53.0           6.0
Int64Index([2001, 2002, 2003, 2004, 2005], dtype='int64', name='Year')

In [110]:
import Quandl
import pandas as pd
import pickle

api_key = open('C:/Users/Matthew Madden/Documents/myquandlkey.txt','r').read()

def state_list():
    fiddy_states = pd.read_html('https://simple.wikipedia.org/wiki/List_of_U.S._states')
    return fiddy_states[0][0][1:]

def grab_initial_state_data():
    states = state_list()
    
    main_df = pd.DataFrame()

    for abbv in states:
        query = "FMAC/HPI_"+str(abbv)
        df = Quandl.get(query, authtoken=api_key)
        df.columns = [abbv]
        print(query)
        if main_df.empty:
            main_df = df
        else:
            main_df = main_df.join(df)
    pickle_out = open('fiddy_states.pickle','wb')
    pickle.dump(main_df,pickle_out)
    pickle_out.close()
        
grab_initial_state_data()

FMAC/HPI_AL
FMAC/HPI_AK
FMAC/HPI_AZ
FMAC/HPI_AR
FMAC/HPI_CA
FMAC/HPI_CO
FMAC/HPI_CT
FMAC/HPI_DE
FMAC/HPI_FL
FMAC/HPI_GA
FMAC/HPI_HI
FMAC/HPI_ID
FMAC/HPI_IL
FMAC/HPI_IN
FMAC/HPI_IA
FMAC/HPI_KS
FMAC/HPI_KY
FMAC/HPI_LA
FMAC/HPI_ME
FMAC/HPI_MD
FMAC/HPI_MA
FMAC/HPI_MI
FMAC/HPI_MN
FMAC/HPI_MS
FMAC/HPI_MO
FMAC/HPI_MT
FMAC/HPI_NE
FMAC/HPI_NV
FMAC/HPI_NH
FMAC/HPI_NJ
FMAC/HPI_NM
FMAC/HPI_NY
FMAC/HPI_NC
FMAC/HPI_ND
FMAC/HPI_OH
FMAC/HPI_OK
FMAC/HPI_OR
FMAC/HPI_PA
FMAC/HPI_RI
FMAC/HPI_SC
FMAC/HPI_SD
FMAC/HPI_TN
FMAC/HPI_TX
FMAC/HPI_UT
FMAC/HPI_VT
FMAC/HPI_VA
FMAC/HPI_WA
FMAC/HPI_WV
FMAC/HPI_WI
FMAC/HPI_WY

In [111]:
pickle_in = open('fiddy_states.pickle','rb')
HPI_data = pickle.load(pickle_in)
print(HPI_data)

                    AL          AK          AZ          AR          CA  \
Date
1975-01-31   35.074411   34.426688   29.038334   36.723834   15.648007
1975-02-28   35.399783   34.937084   29.486154   37.102892   15.702673
1975-03-31   35.749926   35.459711   29.911971   37.436699   15.888042
1975-04-30   36.137895   36.005407   30.243669   37.700854   16.197799
1975-05-31   36.482853   36.601944   30.416235   37.924571   16.461036
1975-06-30   36.666283   37.241454   30.366124   38.134740   16.581623
1975-07-31   36.633167   37.881816   30.075247   38.307819   16.706623
1975-08-31   36.430305   38.465756   29.626764   38.408049   16.927667
1975-09-30   36.183891   38.974331   29.163171   38.411443   17.172787
1975-10-31   36.052125   39.435371   28.909233   38.384339   17.399851
1975-11-30   36.125862   39.844795   29.029356   38.454276   17.550999
1975-12-31   36.433545   40.183635   29.391955   38.648128   17.672618
1976-01-31   36.953841   40.455250   29.760683   38.917496   17.848665
1976-02-29   37.564761   40.683247   30.036190   39.258358   18.054153
1976-03-31   38.109426   40.894246   30.190373   39.672972   18.315386
1976-04-30   38.489785   41.100804   30.232013   40.124945   18.613219
1976-05-31   38.701034   41.306174   30.199446   40.537446   18.843228
1976-06-30   38.788125   41.507096   30.142097   40.884929   19.071853
1976-07-31   38.818702   41.680934   30.119382   41.213948   19.373148
1976-08-31   38.811441   41.818172   30.162700   41.543579   19.679180
1976-09-30   38.789709   41.983272   30.246789   41.801832   19.954879
1976-10-31   38.831162   42.233919   30.407527   41.943037   20.244830
1976-11-30   38.988065   42.563652   30.628717   42.026614   20.597962
1976-12-31   39.168105   42.954323   30.788519   42.132280   20.948483
1977-01-31   39.262801   43.367770   30.877020   42.334488   21.315237
1977-02-28   39.297318   43.749870   31.001949   42.653732   21.792911
1977-03-31   39.345653   44.056945   31.262379   43.019292   22.381060
1977-04-30   39.521547   44.292601   31.582496   43.341648   22.959191
1977-05-31   39.842791   44.502497   31.848398   43.613213   23.547088
1977-06-30   40.270471   44.720391   32.168038   43.904066   24.144100
...                ...         ...         ...         ...         ...
2013-07-31  121.215117  165.926453  140.477474  128.877522  162.765161
2013-08-31  121.109157  165.606306  141.676276  128.374882  164.476695
2013-09-30  120.619628  164.922554  142.392384  127.757454  165.633054
2013-10-31  119.928084  164.222778  142.963141  127.193587  166.158763
2013-11-30  119.407495  163.792317  143.215336  126.871843  166.188235
2013-12-31  119.367505  163.707496  143.371666  126.828690  166.715808
2014-01-31  119.910384  163.996388  143.926692  127.000122  167.942320
2014-02-28  120.752221  164.827354  144.753455  127.425425  169.841875
2014-03-31  121.503997  166.173085  145.574207  127.905429  172.079625
2014-04-30  122.208213  167.576641  146.433840  128.409616  174.056724
2014-05-31  123.002564  168.836462  147.268948  129.025398  175.493725
2014-06-30  123.910830  169.911021  147.945030  129.671647  176.697743
2014-07-31  124.676311  170.616445  148.261455  130.423827  177.879061
2014-08-31  124.914120  170.774271  148.065446  131.218422  178.440078
2014-09-30  124.429500  170.366456  147.872225  131.573349  178.463928
2014-10-31  123.615484  169.596922  148.479655  131.373440  178.563992
2014-11-30  123.060111  168.786765  149.627985  130.749147  178.737160
2014-12-31  122.927558  168.298649  150.497442  129.950020  179.149760
2015-01-31  123.155415  168.291054  151.130860  129.419341  179.978947
2015-02-28  123.588267  168.801511  152.157826  129.438965  181.556468
2015-03-31  124.352449  169.931629  153.527659  130.019730  184.196729
2015-04-30  125.422295  171.641040  155.002905  131.005168  186.714609
2015-05-31  126.563119  173.605536  156.358614  132.098380  188.662719
2015-06-30  127.484547  175.299267  157.498528  132.953470  190.173144
2015-07-31  127.918585  176.321279  158.614811  133.596952  191.297046
2015-08-31  127.834741  176.681780  159.614925  134.239245  192.224093
2015-09-30  127.369884  176.507135  160.468601  134.921128  192.662652
2015-10-31  126.959547  176.039189  160.986296  135.629385  192.707032
2015-11-30  126.675821  175.745100  161.525655  136.383688  192.838509
2015-12-31  126.864758  175.771425  162.139808  137.115932  193.218303

                    CO          CT          DE          FL          GA  \
Date
1975-01-31   19.789021   24.519652   27.196223   31.044385   30.937945
1975-02-28   19.980888   25.046793   27.242465   32.266754   30.650642
1975-03-31   20.177398   25.442231   27.316899   34.064311   30.528512
1975-04-30   20.373025   25.659242   27.461158   36.270704   30.592387
1975-05-31   20.546505   25.717050   27.700146   36.548312   30.709598
1975-06-30   20.698815   25.673165   27.979874   34.933357   30.741574
1975-07-31   20.807076   25.619251   28.224805   33.686356   30.633637
1975-08-31   20.810907   25.608480   28.428171   33.088733   30.389780
1975-09-30   20.738028   25.659209   28.591899   32.948736   30.048061
1975-10-31   20.704089   25.773899   28.690170   33.080612   29.767660
1975-11-30   20.804521   25.967115   28.737392   33.322221   29.680384
1975-12-31   21.013535   26.184672   28.763520   33.458260   29.733364
1976-01-31   21.244803   26.353299   28.765833   33.435908   29.817126
1976-02-29   21.455489   26.455609   28.749861   33.486942   29.840229
1976-03-31   21.658842   26.507643   28.748318   34.060403   29.814713
1976-04-30   21.837791   26.552132   28.807868   35.284359   29.870887
1976-05-31   21.953557   26.626879   28.900439   35.605929   30.098681
1976-06-30   22.019815   26.770244   28.954249   34.742526   30.517935
1976-07-31   22.044991   26.977875   28.957693   34.127460   30.968162
1976-08-31   22.045908   27.146910   28.930252   33.990901   31.195446
1976-09-30   22.083922   27.228953   28.899062   34.085649   31.220193
1976-10-31   22.232466   27.310083   28.908625   34.197937   31.138686
1976-11-30   22.492246   27.371612   28.997701   34.275170   31.025594
1976-12-31   22.761188   27.334380   29.164097   34.122866   30.965081
1977-01-31   22.967540   27.267012   29.380177   33.617196   30.956080
1977-02-28   23.142489   27.247196   29.601942   32.922185   31.005314
1977-03-31   23.338132   27.326217   29.765476   33.043212   31.113002
1977-04-30   23.609744   27.616511   29.833424   34.810141   31.277489
1977-05-31   23.955106   28.104250   29.822078   36.046757   31.474969
1977-06-30   24.362306   28.660606   29.794340   35.607575   31.687182
...                ...         ...         ...         ...         ...
2013-07-31  131.154921  134.395293  145.840462  141.079480  107.094053
2013-08-31  131.487534  134.477134  146.452829  142.385652  107.666510
2013-09-30  131.177622  133.639471  146.453945  143.295939  108.263059
2013-10-31  130.933461  132.339044  145.946886  144.008392  108.823799
2013-11-30  130.820006  130.844936  145.083083  144.775030  109.069510
2013-12-31  130.812655  129.342406  144.237601  144.883347  109.001853
2014-01-31  131.298261  128.495242  143.754022  144.336594  108.860050
2014-02-28  132.646534  128.505800  143.754568  144.823895  109.046997
2014-03-31  134.780111  129.184813  144.293080  146.770989  110.232587
2014-04-30  136.970579  130.540148  145.483833  148.882321  111.993181
2014-05-31  138.795858  132.492085  147.044912  150.668902  113.528121
2014-06-30  140.034214  134.009086  148.549189  152.072161  114.893582
2014-07-31  140.667251  134.112763  149.740596  152.790631  115.754982
2014-08-31  141.223587  133.346518  150.442514  153.202308  116.005624
2014-09-30  141.834794  132.529204  150.504791  153.863933  115.978628
2014-10-31  142.372948  131.869992  149.877110  154.503979  115.966479
2014-11-30  142.835665  131.021137  148.925398  155.024564  115.795930
2014-12-31  143.395534  129.859910  148.026104  155.727461  115.546698
2015-01-31  144.552602  128.921906  147.393933  156.674559  115.902895
2015-02-28  146.630536  128.782625  147.300302  158.271446  116.910156
2015-03-31  149.245814  129.667448  147.927912  160.191362  118.491171
2015-04-30  151.950166  131.309242  149.210665  162.109837  120.256525
2015-05-31  154.406655  133.135295  150.616935  164.474603  121.689074
2015-06-30  156.240069  134.550700  151.412222  166.826795  122.669398
2015-07-31  157.408365  135.132635  151.454146  168.612577  123.235453
2015-08-31  157.903240  134.561730  151.331741  169.591568  123.620657
2015-09-30  158.103577  133.196545  151.535302  170.313006  124.003290
2015-10-31  158.220238  132.027419  152.259259  171.405666  124.197867
2015-11-30  157.778086  131.330794  153.288100  172.412780  123.940990
2015-12-31  157.710565  130.209494  154.293963  173.265861  123.570173

               ...              SD          TN          TX          UT  \
Date           ...
1975-01-31     ...       37.947511   32.253211   32.663795   24.487270
1975-02-28     ...       37.529995   32.298775   33.001967   24.888892
1975-03-31     ...       37.104975   32.389441   33.606352   25.243099
1975-04-30     ...       36.682781   32.521562   34.472694   25.513829
1975-05-31     ...       36.300359   32.671314   34.740937   25.686152
1975-06-30     ...       36.014941   32.826271   34.323390   25.740871
1975-07-31     ...       35.835798   32.978646   34.035249   25.685409
1975-08-31     ...       35.712234   33.143220   33.996312   25.591890
1975-09-30     ...       35.614177   33.372399   34.073595   25.551460
1975-10-31     ...       35.549857   33.724802   34.191885   25.675519
1975-11-30     ...       35.538186   34.193528   34.416682   25.998189
1975-12-31     ...       35.603563   34.620852   34.623480   26.383200
1976-01-31     ...       35.760648   34.832745   34.752102   26.746447
1976-02-29     ...       36.011418   34.823865   35.052952   27.103930
1976-03-31     ...       36.329893   34.746220   35.784148   27.432574
1976-04-30     ...       36.665287   34.764389   36.822771   27.721458
1976-05-31     ...       36.983219   34.833552   37.143364   27.943523
1976-06-30     ...       37.271235   34.816668   36.749201   28.067725
1976-07-31     ...       37.556046   34.753793   36.551442   28.188468
1976-08-31     ...       37.848102   34.740549   36.542569   28.352096
1976-09-30     ...       38.085571   34.780289   36.626526   28.491958
1976-10-31     ...       38.200072   34.855843   36.853678   28.630524
1976-11-30     ...       38.197451   34.968389   37.183340   28.850311
1976-12-31     ...       38.164440   35.151169   37.408222   29.172645
1977-01-31     ...       38.174314   35.452609   37.592698   29.535098
1977-02-28     ...       38.259474   35.876971   38.046811   29.913437
1977-03-31     ...       38.457400   36.367184   39.105137   30.348010
1977-04-30     ...       38.817123   36.850021   40.759919   30.828600
1977-05-31     ...       39.337249   37.284380   41.054958   31.300004
1977-06-30     ...       39.963059   37.700468   40.075925   31.742171
...            ...             ...         ...         ...         ...
2013-07-31     ...      144.701093  128.133284  142.842241  141.310437
2013-08-31     ...      145.146531  128.491226  143.430851  141.847430
2013-09-30     ...      145.431054  128.764453  143.729026  141.936842
2013-10-31     ...      145.543378  128.769068  143.929453  141.559428
2013-11-30     ...      145.430938  128.496666  144.128142  140.925859
2013-12-31     ...      145.139484  128.183247  144.485333  140.543932
2014-01-31     ...      144.999480  128.197881  144.924413  140.730842
2014-02-28     ...      145.269741  129.017405  145.872755  141.684856
2014-03-31     ...      146.022733  130.502393  147.673002  143.247219
2014-04-30     ...      147.083545  132.051479  149.723943  144.811951
2014-05-31     ...      148.082600  133.123793  151.531522  145.958746
2014-06-30     ...      148.804409  133.790934  152.945577  146.601414
2014-07-31     ...      149.346014  134.175268  153.944071  146.917855
2014-08-31     ...      149.816381  134.170385  154.811922  147.095058
2014-09-30     ...      150.117805  134.176240  155.408732  147.173527
2014-10-31     ...      150.300945  134.281455  155.698442  146.964510
2014-11-30     ...      150.358034  134.091974  156.073330  146.572619
2014-12-31     ...      150.381358  133.817302  156.484792  146.645569
2015-01-31     ...      150.639370  133.926772  157.037788  147.414937
2015-02-28     ...      151.343236  134.701699  158.259143  148.777408
2015-03-31     ...      152.565990  135.997966  160.115656  150.540148
2015-04-30     ...      153.959615  137.505515  162.011914  152.383511
2015-05-31     ...      155.220321  139.100732  163.814793  154.131918
2015-06-30     ...      156.254947  140.365084  165.515942  155.475467
2015-07-31     ...      157.062797  140.998079  166.677529  156.281979
2015-08-31     ...      157.581914  141.266203  166.975700  156.825302
2015-09-30     ...      157.834226  141.482907  167.092503  157.360943
2015-10-31     ...      157.915430  141.683134  167.374223  157.894440
2015-11-30     ...      157.771742  141.806958  167.421030  158.270403
2015-12-31     ...      157.531691  141.668203  167.519974  158.805178

                    VT          VA          WA          WV          WI  \
Date
1975-01-31   26.494380   27.972750   17.483198   42.024706   28.211343
1975-02-28   26.745729   28.260893   17.557350   42.856022   28.594192
1975-03-31   26.988402   28.471866   17.667292   43.724924   28.973625
1975-04-30   27.209138   28.623304   17.791671   44.634955   29.314132
1975-05-31   27.403607   28.738495   17.893931   45.574712   29.590366
1975-06-30   27.580495   28.842825   17.997872   46.493314   29.795897
1975-07-31   27.732502   29.007845   18.126551   47.311925   29.947178
1975-08-31   27.840383   29.196152   18.212706   47.968225   30.069924
1975-09-30   27.909922   29.268541   18.218235   48.399997   30.232651
1975-10-31   27.957570   29.231891   18.230912   48.569598   30.437729
1975-11-30   27.985043   29.150809   18.362779   48.542730   30.598902
1975-12-31   27.987427   29.046905   18.585370   48.428034   30.682197
1976-01-31   27.964794   28.969819   18.814439   48.302744   30.712991
1976-02-29   27.929011   29.027938   19.046047   48.239106   30.715488
1976-03-31   27.910877   29.224123   19.272997   48.256591   30.744946
1976-04-30   27.952973   29.452537   19.484542   48.292141   30.878202
1976-05-31   28.069042   29.683216   19.721968   48.288793   31.106285
1976-06-30   28.246902   29.879660   20.039395   48.234306   31.308942
1976-07-31   28.466818   30.021300   20.433948   48.137517   31.451609
1976-08-31   28.697972   30.206953   20.771902   48.041126   31.613939
1976-09-30   28.907163   30.403155   20.954522   48.005305   31.818353
1976-10-31   29.072449   30.533640   21.071408   48.045883   32.021104
1976-11-30   29.198614   30.648929   21.245894   48.163489   32.258549
1976-12-31   29.310340   30.735936   21.457536   48.379095   32.564182
1977-01-31   29.433767   30.796653   21.614025   48.711505   32.905130
1977-02-28   29.584940   30.908678   21.782894   49.148649   33.321610
1977-03-31   29.778558   31.108231   22.105547   49.664978   33.819538
1977-04-30   30.026885   31.365452   22.611436   50.245282   34.305196
1977-05-31   30.333959   31.671131   23.159356   50.820980   34.782824
1977-06-30   30.690482   32.008573   23.653402   51.319724   35.372574
...                ...         ...         ...         ...         ...
2013-07-31  161.001066  167.176373  147.042550  135.626211  119.657603
2013-08-31  161.645169  167.168704  147.496872  136.145875  120.049367
2013-09-30  161.853780  166.669309  147.290317  136.424058  119.696618
2013-10-31  161.519964  165.828617  146.743915  136.646200  118.747180
2013-11-30  160.555967  164.802604  145.709576  136.777760  117.620184
2013-12-31  159.458412  164.161731  144.752615  136.741859  116.530332
2014-01-31  158.872425  164.113689  144.800109  136.629751  115.796211
2014-02-28  158.950818  165.008517  146.282034  136.583226  116.103092
2014-03-31  159.567304  166.920543  148.919929  136.769066  117.479944
2014-04-30  160.642018  168.997043  151.695733  137.278259  119.177582
2014-05-31  161.878629  170.612562  153.920896  138.148799  120.817900
2014-06-30  162.796749  171.547292  155.671727  139.349581  122.103855
2014-07-31  162.981876  171.655777  156.917877  140.734668  122.791981
2014-08-31  162.295394  171.137010  157.212214  142.026356  122.772834
2014-09-30  160.955478  170.341158  156.796858  142.805472  122.374315
2014-10-31  159.376853  169.681076  156.627785  142.745489  121.854905
2014-11-30  158.077688  169.273957  156.914149  142.016867  120.922173
2014-12-31  157.407364  168.769493  157.155764  141.228513  119.733466
2015-01-31  157.449784  168.195077  157.759522  140.914125  119.160823
2015-02-28  158.198804  168.393800  159.535546  141.322001  119.674839
2015-03-31  159.726887  169.740807  162.281196  142.421483  120.977092
2015-04-30  161.993573  171.572978  165.235086  143.895742  122.696719
2015-05-31  164.527890  173.333492  167.866279  145.185501  124.680262
2015-06-30  166.442406  174.591514  170.031878  145.801395  126.150580
2015-07-31  167.227411  175.013409  171.664677  145.734115  126.649107
2015-08-31  167.044215  175.011231  172.563505  145.319274  126.570471
2015-09-30  166.254676  174.878090  172.972875  144.846359  126.234618
2015-10-31  165.122565  174.416078  173.694748  144.566132  126.028231
2015-11-30  163.811187  173.860688  174.673587  144.394098  126.011460
2015-12-31  162.607060  173.281826  175.678257  143.959639  126.142440

                    WY
Date
1975-01-31   31.763481
1975-02-28   32.169075
1975-03-31   32.604698
1975-04-30   33.069949
1975-05-31   33.544935
1975-06-30   34.020039
1975-07-31   34.484220
1975-08-31   34.910439
1975-09-30   35.278249
1975-10-31   35.560589
1975-11-30   35.758460
1975-12-31   35.900927
1976-01-31   36.022267
1976-02-29   36.168044
1976-03-31   36.367217
1976-04-30   36.627519
1976-05-31   36.970940
1976-06-30   37.436003
1976-07-31   38.005593
1976-08-31   38.601370
1976-09-30   39.193214
1976-10-31   39.794319
1976-11-30   40.360216
1976-12-31   40.816936
1977-01-31   41.171246
1977-02-28   41.485902
1977-03-31   41.797430
1977-04-30   42.124011
1977-05-31   42.505179
1977-06-30   43.001444
...                ...
2013-07-31  174.087649
2013-08-31  174.564747
2013-09-30  174.606992
2013-10-31  174.331697
2013-11-30  173.953171
2013-12-31  173.626902
2014-01-31  173.564407
2014-02-28  174.058200
2014-03-31  175.094099
2014-04-30  176.455175
2014-05-31  177.951557
2014-06-30  179.269842
2014-07-31  180.054151
2014-08-31  180.336368
2014-09-30  180.431158
2014-10-31  180.551365
2014-11-30  180.706900
2014-12-31  180.846054
2015-01-31  181.030800
2015-02-28  181.384191
2015-03-31  182.162731
2015-04-30  183.444418
2015-05-31  185.039324
2015-06-30  186.657220
2015-07-31  187.878922
2015-08-31  188.303144
2015-09-30  187.954528
2015-10-31  186.973998
2015-11-30  185.550138
2015-12-31  184.196518

[492 rows x 50 columns]

In [112]:
HPI_data.to_pickle('pickle.pickle')
HPI_data2 = pd.read_pickle('pickle.pickle')
print(HPI_data2)

                    AL          AK          AZ          AR          CA  \
Date
1975-01-31   35.074411   34.426688   29.038334   36.723834   15.648007
1975-02-28   35.399783   34.937084   29.486154   37.102892   15.702673
1975-03-31   35.749926   35.459711   29.911971   37.436699   15.888042
1975-04-30   36.137895   36.005407   30.243669   37.700854   16.197799
1975-05-31   36.482853   36.601944   30.416235   37.924571   16.461036
1975-06-30   36.666283   37.241454   30.366124   38.134740   16.581623
1975-07-31   36.633167   37.881816   30.075247   38.307819   16.706623
1975-08-31   36.430305   38.465756   29.626764   38.408049   16.927667
1975-09-30   36.183891   38.974331   29.163171   38.411443   17.172787
1975-10-31   36.052125   39.435371   28.909233   38.384339   17.399851
1975-11-30   36.125862   39.844795   29.029356   38.454276   17.550999
1975-12-31   36.433545   40.183635   29.391955   38.648128   17.672618
1976-01-31   36.953841   40.455250   29.760683   38.917496   17.848665
1976-02-29   37.564761   40.683247   30.036190   39.258358   18.054153
1976-03-31   38.109426   40.894246   30.190373   39.672972   18.315386
1976-04-30   38.489785   41.100804   30.232013   40.124945   18.613219
1976-05-31   38.701034   41.306174   30.199446   40.537446   18.843228
1976-06-30   38.788125   41.507096   30.142097   40.884929   19.071853
1976-07-31   38.818702   41.680934   30.119382   41.213948   19.373148
1976-08-31   38.811441   41.818172   30.162700   41.543579   19.679180
1976-09-30   38.789709   41.983272   30.246789   41.801832   19.954879
1976-10-31   38.831162   42.233919   30.407527   41.943037   20.244830
1976-11-30   38.988065   42.563652   30.628717   42.026614   20.597962
1976-12-31   39.168105   42.954323   30.788519   42.132280   20.948483
1977-01-31   39.262801   43.367770   30.877020   42.334488   21.315237
1977-02-28   39.297318   43.749870   31.001949   42.653732   21.792911
1977-03-31   39.345653   44.056945   31.262379   43.019292   22.381060
1977-04-30   39.521547   44.292601   31.582496   43.341648   22.959191
1977-05-31   39.842791   44.502497   31.848398   43.613213   23.547088
1977-06-30   40.270471   44.720391   32.168038   43.904066   24.144100
...                ...         ...         ...         ...         ...
2013-07-31  121.215117  165.926453  140.477474  128.877522  162.765161
2013-08-31  121.109157  165.606306  141.676276  128.374882  164.476695
2013-09-30  120.619628  164.922554  142.392384  127.757454  165.633054
2013-10-31  119.928084  164.222778  142.963141  127.193587  166.158763
2013-11-30  119.407495  163.792317  143.215336  126.871843  166.188235
2013-12-31  119.367505  163.707496  143.371666  126.828690  166.715808
2014-01-31  119.910384  163.996388  143.926692  127.000122  167.942320
2014-02-28  120.752221  164.827354  144.753455  127.425425  169.841875
2014-03-31  121.503997  166.173085  145.574207  127.905429  172.079625
2014-04-30  122.208213  167.576641  146.433840  128.409616  174.056724
2014-05-31  123.002564  168.836462  147.268948  129.025398  175.493725
2014-06-30  123.910830  169.911021  147.945030  129.671647  176.697743
2014-07-31  124.676311  170.616445  148.261455  130.423827  177.879061
2014-08-31  124.914120  170.774271  148.065446  131.218422  178.440078
2014-09-30  124.429500  170.366456  147.872225  131.573349  178.463928
2014-10-31  123.615484  169.596922  148.479655  131.373440  178.563992
2014-11-30  123.060111  168.786765  149.627985  130.749147  178.737160
2014-12-31  122.927558  168.298649  150.497442  129.950020  179.149760
2015-01-31  123.155415  168.291054  151.130860  129.419341  179.978947
2015-02-28  123.588267  168.801511  152.157826  129.438965  181.556468
2015-03-31  124.352449  169.931629  153.527659  130.019730  184.196729
2015-04-30  125.422295  171.641040  155.002905  131.005168  186.714609
2015-05-31  126.563119  173.605536  156.358614  132.098380  188.662719
2015-06-30  127.484547  175.299267  157.498528  132.953470  190.173144
2015-07-31  127.918585  176.321279  158.614811  133.596952  191.297046
2015-08-31  127.834741  176.681780  159.614925  134.239245  192.224093
2015-09-30  127.369884  176.507135  160.468601  134.921128  192.662652
2015-10-31  126.959547  176.039189  160.986296  135.629385  192.707032
2015-11-30  126.675821  175.745100  161.525655  136.383688  192.838509
2015-12-31  126.864758  175.771425  162.139808  137.115932  193.218303

                    CO          CT          DE          FL          GA  \
Date
1975-01-31   19.789021   24.519652   27.196223   31.044385   30.937945
1975-02-28   19.980888   25.046793   27.242465   32.266754   30.650642
1975-03-31   20.177398   25.442231   27.316899   34.064311   30.528512
1975-04-30   20.373025   25.659242   27.461158   36.270704   30.592387
1975-05-31   20.546505   25.717050   27.700146   36.548312   30.709598
1975-06-30   20.698815   25.673165   27.979874   34.933357   30.741574
1975-07-31   20.807076   25.619251   28.224805   33.686356   30.633637
1975-08-31   20.810907   25.608480   28.428171   33.088733   30.389780
1975-09-30   20.738028   25.659209   28.591899   32.948736   30.048061
1975-10-31   20.704089   25.773899   28.690170   33.080612   29.767660
1975-11-30   20.804521   25.967115   28.737392   33.322221   29.680384
1975-12-31   21.013535   26.184672   28.763520   33.458260   29.733364
1976-01-31   21.244803   26.353299   28.765833   33.435908   29.817126
1976-02-29   21.455489   26.455609   28.749861   33.486942   29.840229
1976-03-31   21.658842   26.507643   28.748318   34.060403   29.814713
1976-04-30   21.837791   26.552132   28.807868   35.284359   29.870887
1976-05-31   21.953557   26.626879   28.900439   35.605929   30.098681
1976-06-30   22.019815   26.770244   28.954249   34.742526   30.517935
1976-07-31   22.044991   26.977875   28.957693   34.127460   30.968162
1976-08-31   22.045908   27.146910   28.930252   33.990901   31.195446
1976-09-30   22.083922   27.228953   28.899062   34.085649   31.220193
1976-10-31   22.232466   27.310083   28.908625   34.197937   31.138686
1976-11-30   22.492246   27.371612   28.997701   34.275170   31.025594
1976-12-31   22.761188   27.334380   29.164097   34.122866   30.965081
1977-01-31   22.967540   27.267012   29.380177   33.617196   30.956080
1977-02-28   23.142489   27.247196   29.601942   32.922185   31.005314
1977-03-31   23.338132   27.326217   29.765476   33.043212   31.113002
1977-04-30   23.609744   27.616511   29.833424   34.810141   31.277489
1977-05-31   23.955106   28.104250   29.822078   36.046757   31.474969
1977-06-30   24.362306   28.660606   29.794340   35.607575   31.687182
...                ...         ...         ...         ...         ...
2013-07-31  131.154921  134.395293  145.840462  141.079480  107.094053
2013-08-31  131.487534  134.477134  146.452829  142.385652  107.666510
2013-09-30  131.177622  133.639471  146.453945  143.295939  108.263059
2013-10-31  130.933461  132.339044  145.946886  144.008392  108.823799
2013-11-30  130.820006  130.844936  145.083083  144.775030  109.069510
2013-12-31  130.812655  129.342406  144.237601  144.883347  109.001853
2014-01-31  131.298261  128.495242  143.754022  144.336594  108.860050
2014-02-28  132.646534  128.505800  143.754568  144.823895  109.046997
2014-03-31  134.780111  129.184813  144.293080  146.770989  110.232587
2014-04-30  136.970579  130.540148  145.483833  148.882321  111.993181
2014-05-31  138.795858  132.492085  147.044912  150.668902  113.528121
2014-06-30  140.034214  134.009086  148.549189  152.072161  114.893582
2014-07-31  140.667251  134.112763  149.740596  152.790631  115.754982
2014-08-31  141.223587  133.346518  150.442514  153.202308  116.005624
2014-09-30  141.834794  132.529204  150.504791  153.863933  115.978628
2014-10-31  142.372948  131.869992  149.877110  154.503979  115.966479
2014-11-30  142.835665  131.021137  148.925398  155.024564  115.795930
2014-12-31  143.395534  129.859910  148.026104  155.727461  115.546698
2015-01-31  144.552602  128.921906  147.393933  156.674559  115.902895
2015-02-28  146.630536  128.782625  147.300302  158.271446  116.910156
2015-03-31  149.245814  129.667448  147.927912  160.191362  118.491171
2015-04-30  151.950166  131.309242  149.210665  162.109837  120.256525
2015-05-31  154.406655  133.135295  150.616935  164.474603  121.689074
2015-06-30  156.240069  134.550700  151.412222  166.826795  122.669398
2015-07-31  157.408365  135.132635  151.454146  168.612577  123.235453
2015-08-31  157.903240  134.561730  151.331741  169.591568  123.620657
2015-09-30  158.103577  133.196545  151.535302  170.313006  124.003290
2015-10-31  158.220238  132.027419  152.259259  171.405666  124.197867
2015-11-30  157.778086  131.330794  153.288100  172.412780  123.940990
2015-12-31  157.710565  130.209494  154.293963  173.265861  123.570173

               ...              SD          TN          TX          UT  \
Date           ...
1975-01-31     ...       37.947511   32.253211   32.663795   24.487270
1975-02-28     ...       37.529995   32.298775   33.001967   24.888892
1975-03-31     ...       37.104975   32.389441   33.606352   25.243099
1975-04-30     ...       36.682781   32.521562   34.472694   25.513829
1975-05-31     ...       36.300359   32.671314   34.740937   25.686152
1975-06-30     ...       36.014941   32.826271   34.323390   25.740871
1975-07-31     ...       35.835798   32.978646   34.035249   25.685409
1975-08-31     ...       35.712234   33.143220   33.996312   25.591890
1975-09-30     ...       35.614177   33.372399   34.073595   25.551460
1975-10-31     ...       35.549857   33.724802   34.191885   25.675519
1975-11-30     ...       35.538186   34.193528   34.416682   25.998189
1975-12-31     ...       35.603563   34.620852   34.623480   26.383200
1976-01-31     ...       35.760648   34.832745   34.752102   26.746447
1976-02-29     ...       36.011418   34.823865   35.052952   27.103930
1976-03-31     ...       36.329893   34.746220   35.784148   27.432574
1976-04-30     ...       36.665287   34.764389   36.822771   27.721458
1976-05-31     ...       36.983219   34.833552   37.143364   27.943523
1976-06-30     ...       37.271235   34.816668   36.749201   28.067725
1976-07-31     ...       37.556046   34.753793   36.551442   28.188468
1976-08-31     ...       37.848102   34.740549   36.542569   28.352096
1976-09-30     ...       38.085571   34.780289   36.626526   28.491958
1976-10-31     ...       38.200072   34.855843   36.853678   28.630524
1976-11-30     ...       38.197451   34.968389   37.183340   28.850311
1976-12-31     ...       38.164440   35.151169   37.408222   29.172645
1977-01-31     ...       38.174314   35.452609   37.592698   29.535098
1977-02-28     ...       38.259474   35.876971   38.046811   29.913437
1977-03-31     ...       38.457400   36.367184   39.105137   30.348010
1977-04-30     ...       38.817123   36.850021   40.759919   30.828600
1977-05-31     ...       39.337249   37.284380   41.054958   31.300004
1977-06-30     ...       39.963059   37.700468   40.075925   31.742171
...            ...             ...         ...         ...         ...
2013-07-31     ...      144.701093  128.133284  142.842241  141.310437
2013-08-31     ...      145.146531  128.491226  143.430851  141.847430
2013-09-30     ...      145.431054  128.764453  143.729026  141.936842
2013-10-31     ...      145.543378  128.769068  143.929453  141.559428
2013-11-30     ...      145.430938  128.496666  144.128142  140.925859
2013-12-31     ...      145.139484  128.183247  144.485333  140.543932
2014-01-31     ...      144.999480  128.197881  144.924413  140.730842
2014-02-28     ...      145.269741  129.017405  145.872755  141.684856
2014-03-31     ...      146.022733  130.502393  147.673002  143.247219
2014-04-30     ...      147.083545  132.051479  149.723943  144.811951
2014-05-31     ...      148.082600  133.123793  151.531522  145.958746
2014-06-30     ...      148.804409  133.790934  152.945577  146.601414
2014-07-31     ...      149.346014  134.175268  153.944071  146.917855
2014-08-31     ...      149.816381  134.170385  154.811922  147.095058
2014-09-30     ...      150.117805  134.176240  155.408732  147.173527
2014-10-31     ...      150.300945  134.281455  155.698442  146.964510
2014-11-30     ...      150.358034  134.091974  156.073330  146.572619
2014-12-31     ...      150.381358  133.817302  156.484792  146.645569
2015-01-31     ...      150.639370  133.926772  157.037788  147.414937
2015-02-28     ...      151.343236  134.701699  158.259143  148.777408
2015-03-31     ...      152.565990  135.997966  160.115656  150.540148
2015-04-30     ...      153.959615  137.505515  162.011914  152.383511
2015-05-31     ...      155.220321  139.100732  163.814793  154.131918
2015-06-30     ...      156.254947  140.365084  165.515942  155.475467
2015-07-31     ...      157.062797  140.998079  166.677529  156.281979
2015-08-31     ...      157.581914  141.266203  166.975700  156.825302
2015-09-30     ...      157.834226  141.482907  167.092503  157.360943
2015-10-31     ...      157.915430  141.683134  167.374223  157.894440
2015-11-30     ...      157.771742  141.806958  167.421030  158.270403
2015-12-31     ...      157.531691  141.668203  167.519974  158.805178

                    VT          VA          WA          WV          WI  \
Date
1975-01-31   26.494380   27.972750   17.483198   42.024706   28.211343
1975-02-28   26.745729   28.260893   17.557350   42.856022   28.594192
1975-03-31   26.988402   28.471866   17.667292   43.724924   28.973625
1975-04-30   27.209138   28.623304   17.791671   44.634955   29.314132
1975-05-31   27.403607   28.738495   17.893931   45.574712   29.590366
1975-06-30   27.580495   28.842825   17.997872   46.493314   29.795897
1975-07-31   27.732502   29.007845   18.126551   47.311925   29.947178
1975-08-31   27.840383   29.196152   18.212706   47.968225   30.069924
1975-09-30   27.909922   29.268541   18.218235   48.399997   30.232651
1975-10-31   27.957570   29.231891   18.230912   48.569598   30.437729
1975-11-30   27.985043   29.150809   18.362779   48.542730   30.598902
1975-12-31   27.987427   29.046905   18.585370   48.428034   30.682197
1976-01-31   27.964794   28.969819   18.814439   48.302744   30.712991
1976-02-29   27.929011   29.027938   19.046047   48.239106   30.715488
1976-03-31   27.910877   29.224123   19.272997   48.256591   30.744946
1976-04-30   27.952973   29.452537   19.484542   48.292141   30.878202
1976-05-31   28.069042   29.683216   19.721968   48.288793   31.106285
1976-06-30   28.246902   29.879660   20.039395   48.234306   31.308942
1976-07-31   28.466818   30.021300   20.433948   48.137517   31.451609
1976-08-31   28.697972   30.206953   20.771902   48.041126   31.613939
1976-09-30   28.907163   30.403155   20.954522   48.005305   31.818353
1976-10-31   29.072449   30.533640   21.071408   48.045883   32.021104
1976-11-30   29.198614   30.648929   21.245894   48.163489   32.258549
1976-12-31   29.310340   30.735936   21.457536   48.379095   32.564182
1977-01-31   29.433767   30.796653   21.614025   48.711505   32.905130
1977-02-28   29.584940   30.908678   21.782894   49.148649   33.321610
1977-03-31   29.778558   31.108231   22.105547   49.664978   33.819538
1977-04-30   30.026885   31.365452   22.611436   50.245282   34.305196
1977-05-31   30.333959   31.671131   23.159356   50.820980   34.782824
1977-06-30   30.690482   32.008573   23.653402   51.319724   35.372574
...                ...         ...         ...         ...         ...
2013-07-31  161.001066  167.176373  147.042550  135.626211  119.657603
2013-08-31  161.645169  167.168704  147.496872  136.145875  120.049367
2013-09-30  161.853780  166.669309  147.290317  136.424058  119.696618
2013-10-31  161.519964  165.828617  146.743915  136.646200  118.747180
2013-11-30  160.555967  164.802604  145.709576  136.777760  117.620184
2013-12-31  159.458412  164.161731  144.752615  136.741859  116.530332
2014-01-31  158.872425  164.113689  144.800109  136.629751  115.796211
2014-02-28  158.950818  165.008517  146.282034  136.583226  116.103092
2014-03-31  159.567304  166.920543  148.919929  136.769066  117.479944
2014-04-30  160.642018  168.997043  151.695733  137.278259  119.177582
2014-05-31  161.878629  170.612562  153.920896  138.148799  120.817900
2014-06-30  162.796749  171.547292  155.671727  139.349581  122.103855
2014-07-31  162.981876  171.655777  156.917877  140.734668  122.791981
2014-08-31  162.295394  171.137010  157.212214  142.026356  122.772834
2014-09-30  160.955478  170.341158  156.796858  142.805472  122.374315
2014-10-31  159.376853  169.681076  156.627785  142.745489  121.854905
2014-11-30  158.077688  169.273957  156.914149  142.016867  120.922173
2014-12-31  157.407364  168.769493  157.155764  141.228513  119.733466
2015-01-31  157.449784  168.195077  157.759522  140.914125  119.160823
2015-02-28  158.198804  168.393800  159.535546  141.322001  119.674839
2015-03-31  159.726887  169.740807  162.281196  142.421483  120.977092
2015-04-30  161.993573  171.572978  165.235086  143.895742  122.696719
2015-05-31  164.527890  173.333492  167.866279  145.185501  124.680262
2015-06-30  166.442406  174.591514  170.031878  145.801395  126.150580
2015-07-31  167.227411  175.013409  171.664677  145.734115  126.649107
2015-08-31  167.044215  175.011231  172.563505  145.319274  126.570471
2015-09-30  166.254676  174.878090  172.972875  144.846359  126.234618
2015-10-31  165.122565  174.416078  173.694748  144.566132  126.028231
2015-11-30  163.811187  173.860688  174.673587  144.394098  126.011460
2015-12-31  162.607060  173.281826  175.678257  143.959639  126.142440

                    WY
Date
1975-01-31   31.763481
1975-02-28   32.169075
1975-03-31   32.604698
1975-04-30   33.069949
1975-05-31   33.544935
1975-06-30   34.020039
1975-07-31   34.484220
1975-08-31   34.910439
1975-09-30   35.278249
1975-10-31   35.560589
1975-11-30   35.758460
1975-12-31   35.900927
1976-01-31   36.022267
1976-02-29   36.168044
1976-03-31   36.367217
1976-04-30   36.627519
1976-05-31   36.970940
1976-06-30   37.436003
1976-07-31   38.005593
1976-08-31   38.601370
1976-09-30   39.193214
1976-10-31   39.794319
1976-11-30   40.360216
1976-12-31   40.816936
1977-01-31   41.171246
1977-02-28   41.485902
1977-03-31   41.797430
1977-04-30   42.124011
1977-05-31   42.505179
1977-06-30   43.001444
...                ...
2013-07-31  174.087649
2013-08-31  174.564747
2013-09-30  174.606992
2013-10-31  174.331697
2013-11-30  173.953171
2013-12-31  173.626902
2014-01-31  173.564407
2014-02-28  174.058200
2014-03-31  175.094099
2014-04-30  176.455175
2014-05-31  177.951557
2014-06-30  179.269842
2014-07-31  180.054151
2014-08-31  180.336368
2014-09-30  180.431158
2014-10-31  180.551365
2014-11-30  180.706900
2014-12-31  180.846054
2015-01-31  181.030800
2015-02-28  181.384191
2015-03-31  182.162731
2015-04-30  183.444418
2015-05-31  185.039324
2015-06-30  186.657220
2015-07-31  187.878922
2015-08-31  188.303144
2015-09-30  187.954528
2015-10-31  186.973998
2015-11-30  185.550138
2015-12-31  184.196518

[492 rows x 50 columns]

In [113]:
#ended at pt7